[env]
TERM="xterm-256color"
[window]
opacity=0.8
blur=true

[font]
normal.family = "SauceCodePro Nerd Font"

[general]
live_config_reload=true
import = [
	"~/.config/alacritty/themes/coolnight.toml"
]

