[env]
TERM="xterm-256color"
[window]
opacity=0.5
blur=true

[font]
normal.family = "SauceCodePro Nerd Font"

[general]
live_config_reload=true
import = [
	"~/.config/alacritty/themes/coolnight.toml"
]

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "Q", mods = "Control|Shift", action = "Quit" },
]
